import type { SubcategoryProductCardItem } from "./types";

const PRODUCT_LIST_ITEMS: SubcategoryProductCardItem[] = [
  {
    id: "6db6eb8a-c00e-4c85-8bd8-6ae76fd4f8d5",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "3-in-1 Fast Charging Cable",
    imageUrl:
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=900&q=80",
    imageRatio: "square",
    priceAmount: "29.90",
    originalPriceAmount: "49.00",
    currencyCode: "GHS",
    discountPercent: 39,
    rating: "4.7",
    reviewCount: 312,
    sellerTag: "Digital Picks",
    isOnSale: true,
    freeDelivery: true,
  },
  {
    id: "mock-mobile-case-matte",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "Matte Shockproof Phone Case",
    imageUrl:
      "https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=900&q=80",
    imageRatio: "portrait",
    priceAmount: "49.00",
    originalPriceAmount: null,
    currencyCode: "GHS",
    discountPercent: null,
    rating: "4.5",
    reviewCount: 218,
    sellerTag: "Case Studio",
    freeDelivery: true,
  },
  {
    id: "mock-gan-20w-charger",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "20W GaN Travel Charger",
    imageUrl:
      "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=900&q=80",
    imageRatio: "portrait",
    priceAmount: "59.00",
    originalPriceAmount: "89.00",
    currencyCode: "GHS",
    discountPercent: 34,
    rating: "4.8",
    reviewCount: 504,
    sellerTag: "Charge Expert",
    isOnSale: true,
  },
  {
    id: "mock-wireless-earbuds-noise",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "Wireless Earbuds Noise Reduction Edition",
    imageUrl:
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=900&q=80",
    imageRatio: "square",
    priceAmount: "199.00",
    originalPriceAmount: "299.00",
    currencyCode: "GHS",
    discountPercent: 33,
    rating: "4.9",
    reviewCount: 889,
    sellerTag: "Audio Lab",
    isOnSale: true,
  },
  {
    id: "mock-phone-stand-alloy",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "Aluminium Foldable Phone Stand",
    imageUrl:
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80",
    imageRatio: "wide",
    priceAmount: "35.00",
    originalPriceAmount: null,
    currencyCode: "GHS",
    discountPercent: null,
    rating: "4.6",
    reviewCount: 143,
    sellerTag: "Desk Setup",
    isNew: true,
  },
  {
    id: "mock-screen-protector-2pack",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "Privacy Screen Protector 2-Pack",
    imageUrl:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80",
    imageRatio: "portrait",
    priceAmount: "24.50",
    originalPriceAmount: "32.00",
    currencyCode: "GHS",
    discountPercent: 23,
    rating: "4.4",
    reviewCount: 96,
    sellerTag: "Shield Hub",
    isOnSale: true,
  },
  {
    id: "mock-power-bank-10000",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "10000mAh Pocket Power Bank",
    imageUrl:
      "https://images.unsplash.com/photo-1609592806596-b43db13895d2?auto=format&fit=crop&w=900&q=80",
    imageRatio: "square",
    priceAmount: "119.00",
    originalPriceAmount: "145.00",
    currencyCode: "GHS",
    discountPercent: 18,
    rating: "4.8",
    reviewCount: 267,
    sellerTag: "Power House",
    freeDelivery: true,
  },
  {
    id: "mock-car-phone-holder",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "360° Magnetic Car Phone Holder",
    imageUrl:
      "https://images.unsplash.com/photo-1544866092-1935c5ef2a8f?auto=format&fit=crop&w=900&q=80",
    imageRatio: "wide",
    priceAmount: "39.90",
    originalPriceAmount: null,
    currencyCode: "GHS",
    discountPercent: null,
    rating: "4.3",
    reviewCount: 71,
    sellerTag: "Drive Smart",
    isNew: true,
  },
  {
    id: "mock-usbc-adapter-hub",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "USB-C Adapter Hub for Phone and Tablet",
    imageUrl:
      "https://images.unsplash.com/photo-1580894908361-967195033215?auto=format&fit=crop&w=900&q=80",
    imageRatio: "portrait",
    priceAmount: "74.00",
    originalPriceAmount: "96.00",
    currencyCode: "GHS",
    discountPercent: 23,
    rating: "4.7",
    reviewCount: 186,
    sellerTag: "Connect Pro",
    isOnSale: true,
  },
  {
    id: "mock-bluetooth-selfie-stick",
    categoryId: "electronics",
    subcategoryId: "mobile-accessories",
    name: "Bluetooth Selfie Stick with Tripod",
    imageUrl:
      "https://images.unsplash.com/photo-1510127034890-ba27508e9f1c?auto=format&fit=crop&w=900&q=80",
    imageRatio: "square",
    priceAmount: "68.00",
    originalPriceAmount: null,
    currencyCode: "GHS",
    discountPercent: null,
    rating: "4.5",
    reviewCount: 154,
    sellerTag: "Creator Gear",
    freeDelivery: true,
  },
];

function cloneProductItem(item: SubcategoryProductCardItem): SubcategoryProductCardItem {
  return { ...item };
}

export async function getProductListBySubcategory(
  categoryId: string,
  subcategoryId: string,
): Promise<SubcategoryProductCardItem[]> {
  return PRODUCT_LIST_ITEMS.filter(
    (item) => item.categoryId === categoryId && item.subcategoryId === subcategoryId,
  ).map(cloneProductItem);
}
